name: Prettier and ESLint

on:
  pull_request:
    branches: ["dev"]
  push:
    branches: ["dev"]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm install -g pnpm && pnpm install --no-frozen-lockfile

      - name: Run Prettier
        run: pnpm run format

      - name: Check code with ESLint
        run: pnpm run lint
